name: Publish Docker Image to Staging Prime Registry

on:
  push:
    branches:
      - main
    tags:
      - "v*"

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-push-prime:
    name: Build and push Docker image to staging prime registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # for rancher-eio/read-vault-secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
        
      - name: "Read vault secrets"
        uses: rancher-eio/read-vault-secrets@7282bf97898cd1c16c89f837e0bb442e6d384c89 # main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials registry | STAGING_PRIME_REGISTRY ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials username | STAGING_PRIME_REGISTRY_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials password | STAGING_PRIME_REGISTRY_PASSWORD ;

        # This encapsulates: login, qemu, build/push
      - name: Build and push image
        if: ${{ github.ref_type == 'tag' }}
        uses: rancher/ecm-distro-tools/actions/publish-image@e72982e61644408c47b5c181e7ea331532d180d1 # master
        with:
          image: rancher-ai-mcp
          tag: ${{ github.ref_name }}
          push-to-prime: true
          push-to-public: false
          prime-registry: ${{ env.STAGING_PRIME_REGISTRY }}
          prime-repo: rancher
          prime-username: ${{ env.STAGING_PRIME_REGISTRY_USERNAME }}
          prime-password: ${{ env.STAGING_PRIME_REGISTRY_PASSWORD }}

      - name: Build and push head image
        if: ${{ github.ref_name == 'main' }}
        uses: rancher/ecm-distro-tools/actions/publish-image@e72982e61644408c47b5c181e7ea331532d180d1 # master
        with:
          image: rancher-ai-mcp
          tag: head
          push-to-prime: false
          push-to-public: true
          public-registry: ${{ env.STAGING_PRIME_REGISTRY }}
          public-repo: rancher
          public-username: ${{ env.STAGING_PRIME_REGISTRY_USERNAME }}
          public-password: ${{ env.STAGING_PRIME_REGISTRY_PASSWORD }}
